version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: qa-api
    build:
      context: ./
    image: qa-api
    depends_on:
      - db
    ports:
      - 8080:8080
    links:
      - db
volumes:
  postgres:
    driver: local
